



import jakarta.validation.Valid;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.example.smartCollege.dto.AuthResponse;
import com.example.smartCollege.dto.LoginRequest;
import com.example.smartCollege.dto.RegisterRequest;
import com.example.smartCollege.service.AuthService;

/**
 * Registration and login endpoints.
 *
 * Requires a valid API key on every call (see ApiKeyAuthFilter).
 * On success, issues JWT access/refresh tokens generated by the separate JwtService module.
 */


@RestController
@RequestMapping("/api/auth")
public class AuthController {

    private final AuthService authService;

    // Manual constructor - replaces @RequiredArgsConstructor
    public AuthController(AuthService authService) {
        this.authService = authService;
    }

    @PostMapping("/register")
    public ResponseEntity<AuthResponse> register(
            @Valid @RequestBody RegisterRequest request) {

        AuthResponse response = authService.register(request);

        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(response);
    }

    @PostMapping("/login")
    public ResponseEntity<AuthResponse> login(
            @Valid @RequestBody LoginRequest request) {

        AuthResponse response = authService.login(request);

        return ResponseEntity.ok(response);
    }
}